### ISSUE TITLE
Move RJ to normalizers

### ISSUE THREAD

**Issue by jgamper** [Peter554/StainTools#10]
oy @Peter554 ! Can I move RJ to normalizers from the augmentors?

**Comment by Peter554** [comment]
It depends if the RJ method is really a normalizer i.e. can it be implemented with a fit and transform method like the other normalisers?

**Comment by jgamper** [comment]
Yes, you right - its just a stain deconvolution method. Not sure where to put it, what about moving rj to utils.rj_utils as I tried in this branch of my fork [LINK](https://github.com/jgamper/Stain_Normalization/tree/moving_rj/utils), and then modified augmentors.Fetcher as such [LINK](https://github.com/jgamper/Stain_Normalization/blob/66e706600e281003516ee77bbb48fa1941d8cae6/augmentors.py#L23)

Let me know what you think boss!

**Comment by Peter554** [comment]
Yes we can merge that in for sure ;)

**Comment by jgamper** [comment]
Pull request #12 , please review, merge if appropriate and close 💃

**Comment by Peter554** [comment]
Merged :D
