### ISSUE TITLE
Abstract class for normalizers?

### ISSUE THREAD

**Issue by jgamper** [Peter554/StainTools#11]
@Peter554 , Given that there are some other methods that are possible to add for stain normalisation, would it make sense to create an abstract base class? Something like

```python
class abstract_normalizer(metaclass=ABCmeta):
     def __init__(self):
      
     @abstractmethod
     def fit():
           raise NotImplementedError("Should implement fit method")
```

**Comment by Peter554** [comment]
Yes that could make a bit more sense. Call me a python noob but I don't really understand @abstractmethod yet. Can you enlighten?

**Comment by jgamper** [comment]
Maybe issue should be labelled as a discussion then. By no means I am a specialist. Let me attempt to describe with an example, maybe that would make more sense :dancer: However, I can be very wrong 

Take Edward for example.. There for each model you have Inference class, however there are just as many inference types as there are models, and you can flexibly glue these together with common sense applied of course. Behind all inference classes, there is a *metaclass* inference, that implements basic/essential methods, that will be used by all the specific inference types, such as variable initialisation, building a graph and computing. All specific inference types will inherit from that *metaclass* inference, and will therefore have basic methods already implemented, will have structure enforced upon them, and can be easily plugged in as part of the whole package.

**Comment by Peter554** [comment]
Yes we should do this. Shall I do or are you keen?

**Comment by Peter554** [comment]
I'm on it

**Comment by Peter554** [comment]
Ok I made a develop branch and have attempted to implement this. Do you want to have a look and if you're happy we'll merge :)

**Comment by jgamper** [comment]
Awesome! Just ran on mine, Im sure you've tested it already anyways! I got lost in branches, merge and I will pull from your repo master branch :face_with_head_bandage:
