### ISSUE TITLE
A bug??

### ISSUE THREAD

**Issue by lily10086** [Peter554/StainTools#2]
LinAlgError                               Traceback (most recent call last)
<ipython-input-15-2e3f8ac98943> in <module>()
      1 n=stainNorm_Macenko.normalizer()
----> 2 n.fit(i1)
      3 normalized=utils.build_stack((i1,n.transform(i2),n.transform(i3),n.transform(i4),n.transform(i5),n.transform(i6)))

/home/liuzhisheng/stain_Normalization/stainNorm_Macenko.pyc in fit(self, target)
     55     def fit(self, target):
     56         target = ut.standardize_brightness(target)
---> 57         self.stain_matrix_target = get_stain_matrix(target)
     58         self.target_concentrations = ut.get_concentrations(target, self.stain_matrix_target)
     59 

/home/liuzhisheng/stain_Normalization/stainNorm_Macenko.pyc in get_stain_matrix(I, beta, alpha)
     25     OD = ut.RGB_to_OD(I).reshape((-1, 3))
     26     OD = (OD[(OD > beta).any(axis=1), :])
---> 27     _, V = np.linalg.eigh(np.cov(OD, rowvar=False))
     28     V = V[:, [2, 1]]
     29     if V[0, 0] < 0: V[:, 0] *= -1

/home/liuzhisheng/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in eigh(a, UPLO)
   1274 
   1275     signature = 'D->dD' if isComplexType(t) else 'd->dd'
-> 1276     w, vt = gufunc(a, signature=signature, extobj=extobj)
   1277     w = w.astype(_realType(result_t), copy=False)
   1278     vt = vt.astype(result_t, copy=False)

/home/liuzhisheng/anaconda2/lib/python2.7/site-packages/numpy/linalg/linalg.pyc in _raise_linalgerror_eigenvalues_nonconvergence(err, flag)
     94 
     95 def _raise_linalgerror_eigenvalues_nonconvergence(err, flag):
---> 96     raise LinAlgError("Eigenvalues did not converge")
     97 
     98 def _raise_linalgerror_svd_nonconvergence(err, flag):

LinAlgError: Eigenvalues did not converge

**Comment by lily10086** [comment]
I use your data..

**Comment by Peter554** [comment]
I see you are using Python 2.7? I have only tested the code with Python 3.5 - that could be part of the problem?

**Comment by lily10086** [comment]
OO，Thanks
