### ISSUE TITLE
Missing to scale stain concentration in VahadaneNormalizer??

### ISSUE THREAD

**Issue by machisuke** [Peter554/StainTools#21]
I read the paper and found we need to scale stain concentration in VahadaneNormalizer.
But maybe, it doesn't implemented in this library, right??

I think, we should fix  `fit` and  `transfer` method.

**Comment by machisuke** [comment]
This is reference from `Vahadane, Abhishek, et al. "Structure-preserving color normalization and sparse stain separation for histological images." IEEE transactions on medical imaging 35.8 (2016): 1962-1971. `

https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=7460968

![image](https://user-images.githubusercontent.com/17138455/42483983-a17c4fee-842b-11e8-8515-53ef2a20019a.png)
****

**Comment by Peter554** [comment]
Yes I see what you mean. I shall be updating this soon and will close the issue after.

**Comment by Peter554** [comment]
Should be fixed now. Let me know if not.

**Comment by UnderscoreAsterisk** [comment]
Hi @Peter554, can you point out the excerpt of code where this is implemented? I cannot seem to find it
