### ISSUE TITLE
stain augmentation seems to modify contrast/intensity but not hue

### ISSUE THREAD

**Issue by kwiechen** [Peter554/StainTools#22]
Hello,
I have tried to augment image patches using different values for sigma1 and 2. Is it possible that this function perturbs contrast or intensity but not hue/color?
Best regards,
Kai

**Comment by Peter554** [comment]
Yes that is true. As implemented here at present we augment the concentration matrix but not the stain matrix (roughly equates to hue). This may or may not be the desired result, so it is good to be aware
