### ISSUE TITLE
ModuleNotFoundError after installation

### ISSUE THREAD

**Issue by ntomita** [Peter554/StainTools#23]
Hi Peter,

I got a ModuleNotFoundError when importing staintools.
Here's the traceback:
```
Traceback (most recent call last):
 File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/staintools/__init__.py", line 1, in <module>
    from .stain_extractors.macenko_stain_extractor import MacenkoStainExtractor
ModuleNotFoundError: No module named 'staintools.stain_extractors'
```
I installed staintools via pip on Ubuntu16.04 with python 3.6. I installed the required library as well.
Do you have any idea why this happens and how to make it work properly?

**Comment by ghost** [comment]
Same here, on ubuntu 16.04, python 3.5.
1. After installing staintools from pip, I could not find the stain_extractors directory in the package directory. Terminal screen for demonstration:
```
scorbie@scorbie-laptop /usr/local/lib/python3.5/dist-packages/staintools
$ ls
__init__.py  reinhard_color_normalizer.py  stain_normalizer.py
__pycache__  stain_augmentor.py            utils
```
2. On [`setup.py`, line 14](https://github.com/Peter554/StainTools/blob/master/setup.py#L14) `setuptools.find_packages()` is used.

3. Browsing the [setuptools documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html?highlight=find_packages#using-find-packages), it seems like `find_packages()` only recognizes packages that contain `__init__.py`, which only `stain_extractors` does not have.

Thus, I think a simple fix of adding `__init__.py` to the `stain_extractors` directory may solve the issue. I'll test it and send you a pull request if it works.

Edit: That worked. Am writing a pull request right now. Until the change gets on its way, one can manually apply the change by manually copying the missing folders and files from Github.

**Comment by ntomita** [comment]
Awesome, thanks! @Scorbie

**Comment by Peter554** [comment]
Yes sorry not sure how I missed that init file
