### ISSUE TITLE
Make `pip install` great again (2) pip install documentation?

### ISSUE THREAD

**Issue by ghost** [Peter554/StainTools#25]
1. Here's a suggestion; Adding the following instructions to the README:

    **Installing spams from pip:**
    ```bash
    $ pip install numpy  # Must be done before installing spams
    $ pip install spams --index-url https://test.pypi.org/simple
    ```

2. Another option for pip users would be adding `spams` to `setup.py`'s `setup`'s `install_require` argument, as the following:
    ```python
    install_requires=[
        'numpy',
        'opencv-python',
        'matplotlib',
        'future',
        'spams',
        ], ...
    ```
    One caveat of this option would be that installation wouldn't be as simple as
    `pip install staintools`, because the `spams` related issues also apply here:
    ```bash
    $ pip install numpy  # Must be done before because of `spams` dependency
    $ pip install staintools --extra-index-url https://test.pypi.org/simple  # also `spams` related
    ```

**Comment by Peter554** [comment]
Thanks, I have added some advice in the readme about adding SPAMS via PyPI test
