### ISSUE TITLE
Negative optical density issue

### ISSUE THREAD

**Issue by ghost** [Peter554/StainTools#28]
It seems on certain images that a negative optical density issue slips through. I ran the documentation code on some proprietary breast cancer H&E stains using python 3.6, and I ran into the error multiple times. I tracked the error to remove_zeros function in misc_utils.py as the check to find a zero is

`mask = (I == 0)`

But Numpy's log function occasionally returns -0.0. I used a hacky fix in convert_RGB_to_OD(I) to prevent the error for now:

`return np.maximum(-1 * np.log(I / 255), np.zeros(I.shape) + 0.1)`

This seems to be working for the time being, but there may be a better way to patch it up.

**Comment by Peter554** [comment]
Thanks. An odd bug but hopefully should be fixed now.
