### ISSUE TITLE
About stain normalization speed.....

### ISSUE THREAD

**Issue by YiyuHong** [Peter554/StainTools#29]
Which one of stain normalization algorithms is fastest? Besides the methods have implemented here.

As I use the Vahadane's method, it cost 1.4s for a 512x512 image. However, I need to run a stain normalization method for thousands of millions of images, and it cost too much time.

**Comment by Peter554** [comment]
This is the main problem with the methods I agree. Unfortunately none are very fast. You may be better off skipping stain normalization and simply apply heavy random data augmentation if training on that many images.
