### ISSUE TITLE
Principal Eigen vectors inversion, based on the principal eigen vector

### ISSUE THREAD

**Issue by dimimal** [Peter554/StainTools#31]
Thank you for open sourcing your code. I have a question regarding the two lines of code below. 
Why you inversed the eigen vectors based on the principal eigen vector's values?
  
```
# Make sure vectors are pointing the right way
        if V[0, 0] < 0: V[:, 0] *= -1
        if V[0, 1] < 0: V[:, 1] *= -1

```

**Comment by Peter554** [comment]
The eigenvectors physically correspond to color vectors in optical density space so they should be elementwise positive. The math doesn't know about this (if x is an eigenvector so is -x). So we have to see if we got the negative one and if so invert. Does that make sense?

**Comment by dimimal** [comment]
Yes @Peter554. But we are flipping the vectors based on the direction of the principal vector. Is there something else that i miss? For example, why we are not taking the absolute value of the whole V array and we just flip the other vectors based on the principal vector's direction?

**Comment by Peter554** [comment]
The eigenvectors are columns of that matrix not rows. So there is no special treatment for the principle eigenvector. I only test one element of the vector as that's enough to check if it points the right way.

**Comment by dimimal** [comment]
@Peter554  Thanks for your help. Could you please provide the macenko stain normalized samples to cross check them with mine? I saw only the original on your drive.

**Comment by dimimal** [comment]
@Peter554 
I would be obliged if you can send me by email the normalized samples you have on your website. 
My email is: dimimallios@gmail.com

Kind regards, 
Dimitris

**Comment by Peter554** [comment]
Given issue #32 I'm having trouble even using the package at the moment but when this resolves I'll try to remember to send you my result.
