### ISSUE TITLE
Pip install broken

### ISSUE THREAD

**Issue by msschwartz21** [Peter554/StainTools#32]
```
  Collecting staintools
  Downloading https://files.pythonhosted.org/packages/02/09/e6facc38145dc02d521c5233165d65768369b9326a9dde7f032a353f8475/staintools-2.1.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-5kh4awl3/staintools/setup.py", line 4, in <module>
        readme = f.read()
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 3940: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-5kh4awl3/staintools/
```

**Comment by msschwartz21** [comment]
After commenting out the following lines,
```
# with open('README.md') as f:
#     readme = f.read()

setup(
    name='staintools',
    version='2.1.1',
    description='A package for tissue image stain normalization, augmentation and more.',
#     long_description=readme,
    author='Peter Byfield',
    author_email='byfield554@gmail.com',
    url='https://github.com/Peter554/StainTools',
    packages=find_packages(exclude=('tests')),
    install_requires=[
        'numpy',
        'opencv-python',
        'spams',
        'matplotlib'
    ]
)
```
I tried installing from a local cloned directory using `pip install -e .` and triggered the following error:
```
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ffbvu0zn/spams/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3qf2_y4e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ffbvu0zn/spams/
```

**Comment by Peter554** [comment]
I haven't seen the first error before regarding readme encoding, just it should be easily fixable.

I'm more concerned about the second one regarding SPAMS. This is a package dependency that gives rather a headache it seems. It was recently made available of PyPI but unfortunately the install `pip install spams` seems very buggy. Ideally that would be fixed or we would get rid of this dependency some how (but so far I haven't found anything suitable - sklearn did seem to have something similar but it was much slower).

**Comment by Peter554** [comment]
I've sent the SPAMS dev team an email to ask about their pip install.

**Comment by fortunechen** [comment]
> After commenting out the following lines,
> 
> ```
> # with open('README.md') as f:
> #     readme = f.read()
> 
> setup(
>     name='staintools',
>     version='2.1.1',
>     description='A package for tissue image stain normalization, augmentation and more.',
> #     long_description=readme,
>     author='Peter Byfield',
>     author_email='byfield554@gmail.com',
>     url='https://github.com/Peter554/StainTools',
>     packages=find_packages(exclude=('tests')),
>     install_requires=[
>         'numpy',
>         'opencv-python',
>         'spams',
>         'matplotlib'
>     ]
> )
> ```
> I tried installing from a local cloned directory using `pip install -e .` and triggered the following error:
> 
> ```
> Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ffbvu0zn/spams/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-3qf2_y4e/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-ffbvu0zn/spams/
> ```

I installed `spams` first by using conda [https://anaconda.org/conda-forge/python-spams](url), and commented `install_requires` lines, then `pip  install -e .` worked.

**Comment by Peter554** [comment]
Thanks @fortunechen. Yes I also used to use the conda distribution of spams. More recently spams was made available on PyPI so I wanted to switch to that to make install simpler (not everyone uses conda). However it seems to be too buggy at the moment so I will consider to revert to conda again.

**Comment by Peter554** [comment]
Response from SPAMS says they are looking into it but don't expect anything too soon. So for now I'll keep this issue open and have updated the README to advise using conda if possible.

> pip install is currently broken due to the dependency on SPAMS. This issue has been raised with the SPAMS developers. In the meantime if you use conda you may have better luck resolving the SPAMS dependency via conda-forge:
> 
> https://anaconda.org/conda-forge/python-spams

**Comment by Peter554** [comment]
Update: 

- `long_description=readme` issue should now be resolved.
- SPAMS install. For now have removed from setup.py and updated README to guide users to the conda option.
