### ISSUE TITLE
The software stops when have a empty tissue image when I tried to process hundreds of images

### ISSUE THREAD

**Issue by 3dimaging** [Peter554/StainTools#34]
I don't think it is a real issue, but when I process lots of images using for loop in python, one blank image with empty tissue will stop the whole process. Can you modified the code and let it do nothing on that image, but keep processing other images? Thank you!

Here is the error message:

~/staintools/tissue_masks/luminosity_threshold_tissue_locator.py", line 27, in get_tissue_mask
    raise TissueMaskException("Empty tissue mask computed")
staintools.miscellaneous.exceptions.TissueMaskException: Empty tissue mask computed

**Comment by Peter554** [comment]
Just use a try catch block inside your loop perhaps? That should let the program keep running and allow you to handle the error as you see appropriate?

**Comment by smujiang** [comment]
When I tried to normalize some image patches. I got the same error.
staintools.miscellaneous.exceptions.TissueMaskException: Empty tissue mask computed

The exception is thrown from the code below:
`
        if mask.sum() == 0:
            raise TissueMaskException("Empty tissue mask computed")
`
I noticed that these two lines do not exist in previous version. Are these really necessary?

**Comment by Peter554** [comment]
Yes I think so. If we found no tissue in that image there is certainly no point to try and stain normalize and it can helpful to have such images pointed out to you. Just catch the exception and handle how you like (probably just skip and make a note that that patch is all background).
