### ISSUE TITLE
Copyright and usage question

### ISSUE THREAD

**Issue by kheffah** [Peter554/StainTools#37]
@Peter554 Thank you so much for open-sourcing your code. The implementations are really nice to follow and are clear. This is immensely helpful to the computational pathology community, myself included. I wanted to ask if you have any specific copyright restrictions on usage and modification of your code **with clear and unambiguous attribution of this repository as the source**. Specifically, I am one of the people who contribute to and regularly use an open-source package called HistomicsTK:

https://github.com/DigitalSlideArchive/HistomicsTK

I would love to integrate some of the implementations you have here, either as-is or with modifications to integrate well with other aspects of the package. Ideally, if things are modified so that they integrate well with HistomicsTK then some of these pipelines can be run on the server-side on a whole-slide level, which is one reason why I cannot simply add StainTools as a dependency. If that is alright with you, I would love if you:

1. Confirm if it is OK to integrate and modify code from this repository other open-access packages.

2. If you agree to the previous point, what copyright notice would you like me to show, and where?

Thank you so much again for this wonderful repo.

**Comment by Peter554** [comment]
Thanks @kheffah for your interest. Yes it would be fine to include staintools in the HistomicsTK project either as is or with modifications. In terms of copyright I don't mind too much but a comment/link in the source code to the staintools project would be appreciated. Any feedback on improvements you find/make would also be appreciated. Thanks.

https://github.com/Peter554/StainTools/blob/master/LICENSE.txt

**Comment by kheffah** [comment]
Wonderful, thank you!
