### ISSUE TITLE
ModuleNotFoundError after installation

### ISSUE THREAD

**Issue by mgibbs1259** [Peter554/StainTools#38]
MacOS Mojave 10.14.6
Python 3.7.4

I installed SPAMS via conda. Then, I installed staintools 2.1.2 via pip, which succeeded. Then, I went to import staintools and received a ModuleNotFoundError. 

I saw a past issue that was similar. Not sure where to go from here. Any help would be appreciated!

**Comment by smujiang** [comment]
I doubte you are not working in the conda enviroment you install the package.
