### ISSUE TITLE
spams??

### ISSUE THREAD

**Issue by liuzhisheng1226** [Peter554/StainTools#5]
home/liuzhisheng/Stain_Normalization/stain_utils.py in <module>()
     11 import numpy as np
     12 import cv2 as cv
---> 13 import spams
     14 import matplotlib.pyplot as plt
     15 
ImportError: No module named spams

How to install spams,when I run pip install spams, No matching distribution found for spams

**Comment by wanghao14** [comment]
@liuzhisheng1226 Referring to [this instrution](http://blog.csdn.net/hjxu2016/article/details/78916625), I installed the spams-python successfully.

**Comment by Peter554** [comment]
https://anaconda.org/conda-forge/python-spams

This is how I installed spams

**Comment by liuzhisheng1226** [comment]
@JisuiWang Thanks ,I installed it use your method.

**Comment by liuzhisheng1226** [comment]
@Peter554 Thanks for your help
