### ISSUE TITLE
How to preserve the normalized picture?

### ISSUE THREAD

**Issue by wanghao14** [Peter554/StainTools#6]
I have used your code like:
`i1=utils.read_image('./data/i1.png')
i2=utils.read_image('./data/i8.tif')
n=stainNorm_Reinhard.Normalizer()
n.fit(i1)
normalized=n.transform(i2)
cv.imwrite('i8_n.tif', normalized)`
but the picture preserved as 'i8_n.tif' looks strange. I want to know how to preserved the normalized picture which looks like in your example.

**Comment by Peter554** [comment]
Can you send a copy of the picture please?

**Comment by wanghao14** [comment]
@Peter554  Thanks for your reply. I find it is because I don't convert the color space from RGB to BGR before I use the 'cv2.imwrite'.

**Comment by Peter554** [comment]
Yes that would be it!
