### ISSUE TITLE
I use your code ,But it does not have a good effect

### ISSUE THREAD

**Issue by liuzhisheng1226** [Peter554/StainTools#7]
![1](https://user-images.githubusercontent.com/19258612/37971018-8609c5aa-3207-11e8-944c-d50cb1270106.jpg)
![2](https://user-images.githubusercontent.com/19258612/37971026-8aa38ca4-3207-11e8-8e01-270558b1e6d1.jpg)
The result is:

![3](https://user-images.githubusercontent.com/19258612/37971211-f69fea7e-3207-11e8-9f41-77406f7fae22.png)

**Comment by liuzhisheng1226** [comment]
I use the following code:
n=stainNorm_Macenko.Normalizer()
n.fit(i1)
normalized=utils.build_stack((i1,n.transform(i2)))

**Comment by liuzhisheng1226** [comment]
And the picture was stained by HE

**Comment by Peter554** [comment]
How do you read the image in? Note that e.g. cv2 reads images as BGR but I expect images in form RGB here. Eg see the read image function in utils.

**Comment by liuzhisheng1226** [comment]
I read images by utils.read_image,And write image by cv2.imwrite

**Comment by Peter554** [comment]
Are ok in this case you need to convert from RGB back to BGR before saving
with cv2. Or visualize with Eg matplotlib imshow function (or the show
function I have in the utilities)

**Comment by liuzhisheng1226** [comment]
Oh,Thanks a lot!!
