### ISSUE TITLE
Reasoning behind using spams package for stain concentrations?

### ISSUE THREAD

**Issue by jgamper** [Peter554/StainTools#8]
Hello @Peter554 , amazing peace of code. thanks! Just wondering what was the reasoning behind using spams for lasso?

**Comment by Peter554** [comment]
Good question! One could probably alternatively use e.g. http://scikit-learn.org/stable/modules/generated/sklearn.linear_model.Lasso.html provided you constrain the weights (concentrations) to be positive. I can't remember if I tried this - perhaps SPAMS was faster..? Also, I use SPAMS elsewhere (e.g. spams.trainDL in the Vahadane method to get the stain matrix) so thought I would be consistent. The Original authors have a MATLAB repo using SPAMS which is probably where I got the idea from: https://github.com/abhishekvahadane/CodeRelease_ColorNormalization
